// <auto-generated />
using System;
using AtividadeAula10.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtividadeAula10.Migrations
{
    [DbContext(typeof(AtividadeAula10Context))]
    [Migration("20200707200740_AddPlataforma")]
    partial class AddPlataforma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtividadeAula10.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Plataforma");
                });

            modelBuilder.Entity("AtividadeAula10.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int?>("PlataformaId");

                    b.Property<double>("Preco");

                    b.HasKey("Id");

                    b.HasIndex("PlataformaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("AtividadeAula10.Models.Produto", b =>
                {
                    b.HasOne("AtividadeAula10.Models.Categoria", "Plataforma")
                        .WithMany("Plataformas")
                        .HasForeignKey("PlataformaId");
                });
#pragma warning restore 612, 618
        }
    }
}
